version: '3.8'
services:
  redis:
    image: redis
    container_name: cache
    restart: unless-stopped
    expose:
      - 6379

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
  
  app:
    build: .
    container_name: app
    restart: always
    volumes:
      - .:/home/app/:ro
      - /home/app/node_modules/
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis


volumes:
  db-data:
    driver: local
